---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
  )
```

# ditherer

This is a very early work in progress. EXPERIMENTAL!

Now using `magick` as the main engine

## Installation
```{r eval = F}
remotes::install_github('cj-holmes/ditherer)
```

```{r}
library(ditherer)
```

Test image
```{r}
img <- 'data-raw/lenna.png'
```

Default settings are to extract a 16 colour palette from the original (resized image)

## Ordered dithering (default)
```{r out.width="50%", fig.show="hold", fig.height=8}
dither(img, original = TRUE)
dither(img, dither = "ordered")
```

## Error diffusion dithering
```{r out.width="50%", fig.show="hold", fig.height=8}
dither(img, original = TRUE)
dither(img, dither = "diffusion")
```

## No dithering
```{r out.width="50%", fig.show="hold", fig.height=8}
dither(img, original = TRUE)
dither(img, dither = "none")
```

